a = float(input("Masukan bilangan 1 : "))
b = float(input("Masukan bilangan 2 : "))
jumlah = float(a) + float(b) 
print("jumlah a ditambah b :", jumlah)
selisih = abs(a - b)
print("selisih a dan b :", selisih)
pembagian = float(a) / float(b)
print("jumlah a dibagi b :", pembagian)
perkalian = float(a) * float(b)
print("jumlah perkalian a dan b :", perkalian)
sisa = float(a) % float(b)
print("jumlah sisa pembagian a dan b :", sisa)
pangkat = float(a) ** float(b)
print("jumlah dari a pangkat b :", pangkat)
loga = math.log10(a)
print("hasil dari log(a) :", loga)
